#!/usr/bin/env python3
"""Write a Codex provider profile that references env_key, never a raw secret."""
import sys
from pathlib import Path

path, provider, name, base, env_key, model = sys.argv[1:7]
Path(path).parent.mkdir(parents=True, exist_ok=True)
Path(path).write_text(
    f"""# Generated by coding-agents-setup-kit; do not hand-edit.
model = "{model}"
model_provider = "{provider}"
[model_providers.{provider}]
name = "{name}"
base_url = "{base}"
env_key = "{env_key}"
wire_api = "responses"
"""
)
