#!/usr/bin/env bash
# __NAME__ - Git Bash / MSYS2 / Cygwin shim, generated by install.ps1 from
# win/lib/bash-shim.sh. Bash cannot run __NAME__.cmd by its bare name, so this
# forwards to the same PowerShell entry point the .cmd uses: one dispatcher, one
# env file (%APPDATA%\coding-agents-kit\env), whichever shell you type in.
# PowerShell and cmd.exe prefer __NAME__.cmd over this file.
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
lib="$(cygpath -w "${here}/../lib")"
ps=pwsh
command -v pwsh >/dev/null 2>&1 || ps=powershell.exe
case "__NAME__" in
  agentkit) exec "${ps}" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "${lib}\Invoke-AgentKit.ps1" "$@" ;;
  agentbox) exec "${ps}" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "${lib}\Invoke-AgentBox.ps1" "$@" ;;
  *)        exec "${ps}" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "${lib}\Invoke-Wrapper.ps1" "__NAME__" "$@" ;;
esac
